services:
  class-board-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/node_modules/.pnpm
    depends_on:
      - class-board-pg
      - class-board-redis
    develop:
      watch:
        - path: ./src
          action: sync
          target: .:/app
    networks:
      - class-board-network
    stdin_open: true
    tty: true
    command: sh -c "pnpm prisma migrate deploy && pnpm dev"

  class-board-pg:
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=classboard_db

    networks:
      - class-board-network
  class-board-redis:
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - class-board-network

networks:
  class-board-network:
    driver: bridge
